# Question 1: Décomposition QR par la méthode Householder

### a. Démontrez que les matrices de réflexion $\mathbf{Q_i}$ sont orthogonales

Nous devons démontrer que les matrices $\mathbf{Q_i}$ sont orthogonales, c'est-à-dire que $\mathbf{Q_i}^T \mathbf{Q_i} = \mathbf{I}$.

La matrice $\mathbf{Q_i}$ est définie comme :
$$\mathbf{Q_i} = \begin{pmatrix} \mathbf{I_i} & 0 \\ 0 & \mathbf{H_{m,i}} \end{pmatrix}$$
où $\mathbf{I_i}$ est la matrice identité de dimension $i \times i$ et $\mathbf{H_{m,i}}$ est la matrice de réflexion de Householder.

Nous devons d'abord montrer que $\mathbf{H_{m,i}}$ est orthogonale, ce qui signifie que $\mathbf{H_{m,i}}^T \mathbf{H_{m,i}} = \mathbf{I}$. Cette propriété peut être démontrée en utilisant les relations suivantes pour $\mathbf{H_{m,i}}$ :
$$\mathbf{H_{m,i}} = \mathbf{I_{m-i}} - 2 \frac{v_{m,i} v_{m,i}^T}{v_{m,i}^T v_{m,i}}$$
où $v_{m,i}$ est un vecteur dépendant de la matrice $A$. En développant le produit $\mathbf{H_{m,i}}^T \mathbf{H_{m,i}}$, on peut vérifier qu'il donne la matrice identité.

Ensuite, pour $\mathbf{Q_i}$, nous avons :
$$\mathbf{Q_i^T Q_i} = \begin{pmatrix} \mathbf{I_i^T} & 0 \\ 0 & \mathbf{H_{m,i}^T} \end{pmatrix} \begin{pmatrix} \mathbf{I_i} & 0 \\ 0 & \mathbf{H_{m,i}} \end{pmatrix} = \begin{pmatrix} \mathbf{I_i} & 0 \\ 0 & \mathbf{I_{m-i}} \end{pmatrix} = \mathbf{I}$$
Ce qui montre que $\mathbf{Q_i}$ est orthogonale.

### b. Démontrez $\mathbf{Q} = \mathbf{Q}_0^T \mathbf{Q}_1^T \dots \mathbf{Q}_{n-2}^T \mathbf{Q}_{n-1}^{T}$ et que la matrice $\mathbf{Q}$ est orthogonale

La matrice $\mathbf{Q}$ dans la décomposition QR par la méthode de Householder est définie comme le produit des matrices $\mathbf{Q_i}$ :
$$\mathbf{Q} = \mathbf{Q_0^T Q_1^T \dots Q_{n-2}^T Q_{n-1}^T}$$
Puisque chaque matrice $\mathbf{Q_i}$ est orthogonale (comme démontré dans la section a), le produit des matrices orthogonales reste orthogonal. Ainsi, la matrice $\mathbf{Q}$ est également orthogonale.
En effet, pour toutes matrices orthogonales $\mathbf{A}$ et $\mathbf{B}$, on a : $\mathbf{A^T A = I}$ et $\mathbf{B^T B = I}$, donc $\mathbf{(A B)^T (A B) = I}$.

### c. Implémentez la fonction *householder_qr* qui prend en argument une matrice A et qui retourne les matrices $\mathbf{Q}$ et $\mathbf{R}$ obtenues par la méthode de Householder.

In [1]:
import numpy as np

def householder_qr(A):
    """
    Effectue la décomposition QR d'une matrice A par la méthode de Householder.
    
    Paramètres:
    A (numpy.ndarray): Matrice d'entrée (m x n).
    
    Retourne:
    Q (numpy.ndarray): Matrice orthogonale (m x n).
    R (numpy.ndarray): Matrice triangulaire supérieure (n x n).
    """
    # Dimensions de la matrice A
    m, n = A.shape
    
    # Initialisation de Q comme la matrice identité de taille m x m
    Q = np.eye(m)
    
    # Processus de décomposition
    for i in range(n):
        # Extraire le vecteur à partir de la i-ième colonne d'A
        x = A[i:m, i]
        
        # Calcul du vecteur v pour la réflexion de Householder
        e1 = np.zeros_like(x)
        e1[0] = 1
        alpha = np.sign(x[0]) * np.linalg.norm(x)
        v = x + alpha * e1
        v = v / np.linalg.norm(v)  # Normaliser le vecteur v
        
        # Appliquer la réflexion à A (notez que nous appliquons H à partir de la sous-matrice d'A)
        A[i:m, i:n] = A[i:m, i:n] - 2 * np.outer(v, np.dot(v.T, A[i:m, i:n]))
        
        # Mettre à jour la matrice Q
        Q[i:m, i:m] = Q[i:m, i:m] - 2 * np.outer(v, np.dot(v.T, Q[i:m, i:m]))
        
        # Affichage de l'état après chaque itération
        print(f"\nAprès itération {i+1}:")
        print("Matrice Q mise à jour:")
        print(Q)
        print("Matrice A après réflexion:")
        print(A)

    # R est la matrice triangulaire supérieure qui reste dans A
    R = A[:n, :]
    
    # Nous ajustons Q pour être de taille m x n, pas m x m
    Q = Q[:, :n]
    
    return Q, R

Puisqu'on manipule plusieurs vecteurs, il y a des erreurs numériques qui s'additionnent et qui finissent par induire une différence dans le résultat.

### d. À l’aide d’une matrice de dimension 4 × 3 de votre choix, testez votre fonction householder_qr et comparez les résultats obtenus avec ceux obtenus à l’aide de la fonction *numpy.linalg.qr*. Les matrices sont-elles exactement les mêmes ? Si non, est-ce un problème ?

In [ ]:
A = np.random.rand(4, 3)  # Exemple de matrice 4x3
Q, R = householder_qr(A)
#ça marche pas avec householder

# Comparaison avec la décomposition QR de numpy
Q_np, R_np = np.linalg.qr(A)

# Affichage des résultats
print("\nMatrice A:")
print(A)
print("\nMatrice Q (Householder):")
print(Q)
print("\nMatrice R (Householder):")
print(R)

# Affichage de la différence entre A et QR
difference = np.dot(Q, R) - A
print("\nDifférence A - QR (Householder):")
print(difference)

# Vérification A = QR avec une tolérance plus stricte
print("\nVérification A = QR (Householder):")
print(np.allclose(np.dot(Q, R), A, atol=1e-8))  # Augmenter la tolérance (atol)

# Affichage des résultats numpy
print("\nMatrice Q (numpy.linalg.qr):")
print(Q_np)
print("\nMatrice R (numpy.linalg.qr):")
print(R_np)

# Comparaison avec numpy.linalg.qr
print("\nVérification A = QR (numpy.linalg.qr):")
print(np.allclose(np.dot(Q_np, R_np), A, atol=1e-8))  # Vérification de la méthode numpy


Après itération 1:
Matrice Q mise à jour:
[[-0.29542458 -0.37956    -0.26673817 -0.8351702 ]
 [-0.37956     0.88878874 -0.07815441 -0.24470526]
 [-0.26673817 -0.07815441  0.9450765  -0.17196815]
 [-0.8351702  -0.24470526 -0.17196815  0.46155934]]
Matrice A après réflexion:
[[-1.02136925e+00 -1.18764976e+00 -1.09165150e+00]
 [ 5.55111512e-17  1.38212191e-01  7.51635698e-02]
 [ 5.55111512e-17  2.44931299e-01  1.56304534e-01]
 [ 1.11022302e-16 -8.80775897e-01 -3.22016335e-01]]

Après itération 2:
Matrice Q mise à jour:
[[-0.29542458 -0.37956    -0.26673817 -0.8351702 ]
 [-0.37956    -0.3452673  -0.40249597  0.52182461]
 [-0.26673817 -0.36255348  0.87032913  0.0046854 ]
 [-0.8351702   0.77799722  0.09682428 -0.17368895]]
Matrice A après réflexion:
[[-1.02136925e+00 -1.18764976e+00 -1.09165150e+00]
 [ 5.55111512e-17 -9.24586465e-01 -3.59400265e-01]
 [ 5.55111512e-17  5.55111512e-17  5.61554755e-02]
 [ 1.11022302e-16 -1.11022302e-16  3.81208829e-02]]

Après itération 3:
Matrice Q mise à jou