# Question 1: Décomposition QR par la méthode Householder

### a. Démontrez que les matrices de réflexion $\mathbf{Q_i}$ sont orthogonales

Nous devons démontrer que les matrices $\mathbf{Q_i}$ sont orthogonales, c'est-à-dire que $\mathbf{Q_i}^T \mathbf{Q_i} = \mathbf{I}$.

La matrice $\mathbf{Q_i}$ est définie comme :
$$\mathbf{Q_i} = \begin{pmatrix} \mathbf{I_i} & 0 \\ 0 & \mathbf{H_{m,i}} \end{pmatrix}$$
où $\mathbf{I_i}$ est la matrice identité de dimension $i \times i$ et $\mathbf{H_{m,i}}$ est la matrice de réflexion de Householder.

Nous devons d'abord montrer que $\mathbf{H_{m,i}}$ est orthogonale, ce qui signifie que $\mathbf{H_{m,i}}^T \mathbf{H_{m,i}} = \mathbf{I}$. Cette propriété peut être démontrée en utilisant les relations suivantes pour $\mathbf{H_{m,i}}$ :
$$\mathbf{H_{m,i}} = \mathbf{I_{m-i}} - 2 \frac{v_{m,i} v_{m,i}^T}{v_{m,i}^T v_{m,i}}$$
où $v_{m,i}$ est un vecteur dépendant de la matrice $A$. En développant le produit $\mathbf{H_{m,i}}^T \mathbf{H_{m,i}}$, on peut vérifier qu'il donne la matrice identité.

Ensuite, pour $\mathbf{Q_i}$, nous avons :
$$\mathbf{Q_i^T Q_i} = \begin{pmatrix} \mathbf{I_i^T} & 0 \\ 0 & \mathbf{H_{m,i}^T} \end{pmatrix} \begin{pmatrix} \mathbf{I_i} & 0 \\ 0 & \mathbf{H_{m,i}} \end{pmatrix} = \begin{pmatrix} \mathbf{I_i} & 0 \\ 0 & \mathbf{I_{m-i}} \end{pmatrix} = \mathbf{I}$$
Ce qui montre que $\mathbf{Q_i}$ est orthogonale.

### b. Démontrez $\mathbf{Q} = \mathbf{Q}_0^T \mathbf{Q}_1^T \dots \mathbf{Q}_{n-2}^T \mathbf{Q}_{n-1}^{T}$ et que la matrice $\mathbf{Q}$ est orthogonale

La matrice $\mathbf{Q}$ dans la décomposition QR par la méthode de Householder est définie comme le produit des matrices $\mathbf{Q_i}$ :
$$\mathbf{Q} = \mathbf{Q_0^T Q_1^T \dots Q_{n-2}^T Q_{n-1}^T}$$
Puisque chaque matrice $\mathbf{Q_i}$ est orthogonale (comme démontré dans la section a), le produit des matrices orthogonales reste orthogonal. Ainsi, la matrice $\mathbf{Q}$ est également orthogonale.
En effet, pour toutes matrices orthogonales $\mathbf{A}$ et $\mathbf{B}$, on a : $\mathbf{A^T A = I}$ et $\mathbf{B^T B = I}$, donc $\mathbf{(A B)^T (A B) = I}$.

### c. Implémentez la fonction *householder_qr* qui prend en argument une matrice A et qui retourne les matrices $\mathbf{Q}$ et $\mathbf{R}$ obtenues par la méthode de Householder.

In [1]:
import numpy as np

def householder_qr(A):
    """
    Effectue la décomposition QR d'une matrice A par la méthode de Householder.
    
    Paramètres:
    A (numpy.ndarray): Matrice d'entrée (m x n).
    
    Retourne:
    Q (numpy.ndarray): Matrice orthogonale (m x n).
    R (numpy.ndarray): Matrice triangulaire supérieure (n x n).
    """
    # Dimensions de la matrice A
    m, n = A.shape
    
    # Initialisation de Q comme la matrice identité de taille m x m
    Q = np.eye(m)
    
    # Processus de décomposition
    for i in range(n):
        # Extraire le vecteur à partir de la i-ième colonne d'A
        x = A[i:m, i]
        
        # Calcul du vecteur v pour la réflexion de Householder
        e1 = np.zeros_like(x)
        e1[0] = 1
        alpha = np.sign(x[0]) * np.linalg.norm(x)
        v = x + alpha * e1
        v = v / np.linalg.norm(v)  # Normaliser le vecteur v
        
        # Appliquer la réflexion à A (notez que nous appliquons H à partir de la sous-matrice d'A)
        A[i:m, i:n] = A[i:m, i:n] - 2 * np.outer(v, np.dot(v.T, A[i:m, i:n]))
        
        # Mettre à jour la matrice Q
        Q[i:m, i:m] = Q[i:m, i:m] - 2 * np.outer(v, np.dot(v.T, Q[i:m, i:m]))
        
        # Affichage de l'état après chaque itération
        print(f"\nAprès itération {i+1}:")
        print("Matrice Q mise à jour:")
        print(Q)
        print("Matrice A après réflexion:")
        print(A)

    # R est la matrice triangulaire supérieure qui reste dans A
    R = A[:n, :]
    
    # Nous ajustons Q pour être de taille m x n, pas m x m
    Q = Q[:, :n]
    
    return Q, R

Puisqu'on manipule plusieurs vecteurs, il y a des erreurs numériques qui s'additionnent et qui finissent par induire une différence dans le résultat.

### d. À l’aide d’une matrice de dimension 4 × 3 de votre choix, testez votre fonction householder_qr et comparez les résultats obtenus avec ceux obtenus à l’aide de la fonction *numpy.linalg.qr*. Les matrices sont-elles exactement les mêmes ? Si non, est-ce un problème ?

In [ ]:
A = np.random.rand(4, 3)  # Exemple de matrice 4x3
Q, R = householder_qr(A)
#ça marche pas avec householder

# Comparaison avec la décomposition QR de numpy
Q_np, R_np = np.linalg.qr(A)

# Affichage des résultats
print("\nMatrice A:")
print(A)
print("\nMatrice Q (Householder):")
print(Q)
print("\nMatrice R (Householder):")
print(R)

# Affichage de la différence entre A et QR
difference = np.dot(Q, R) - A
print("\nDifférence A - QR (Householder):")
print(difference)

# Vérification A = QR avec une tolérance plus stricte
print("\nVérification A = QR (Householder):")
print(np.allclose(np.dot(Q, R), A, atol=1e-8))  # Augmenter la tolérance (atol)

# Affichage des résultats numpy
print("\nMatrice Q (numpy.linalg.qr):")
print(Q_np)
print("\nMatrice R (numpy.linalg.qr):")
print(R_np)

# Comparaison avec numpy.linalg.qr
print("\nVérification A = QR (numpy.linalg.qr):")
print(np.allclose(np.dot(Q_np, R_np), A, atol=1e-8))  # Vérification de la méthode numpy


Après itération 1:
Matrice Q mise à jour:
[[-0.29542458 -0.37956    -0.26673817 -0.8351702 ]
 [-0.37956     0.88878874 -0.07815441 -0.24470526]
 [-0.26673817 -0.07815441  0.9450765  -0.17196815]
 [-0.8351702  -0.24470526 -0.17196815  0.46155934]]
Matrice A après réflexion:
[[-1.02136925e+00 -1.18764976e+00 -1.09165150e+00]
 [ 5.55111512e-17  1.38212191e-01  7.51635698e-02]
 [ 5.55111512e-17  2.44931299e-01  1.56304534e-01]
 [ 1.11022302e-16 -8.80775897e-01 -3.22016335e-01]]

Après itération 2:
Matrice Q mise à jour:
[[-0.29542458 -0.37956    -0.26673817 -0.8351702 ]
 [-0.37956    -0.3452673  -0.40249597  0.52182461]
 [-0.26673817 -0.36255348  0.87032913  0.0046854 ]
 [-0.8351702   0.77799722  0.09682428 -0.17368895]]
Matrice A après réflexion:
[[-1.02136925e+00 -1.18764976e+00 -1.09165150e+00]
 [ 5.55111512e-17 -9.24586465e-01 -3.59400265e-01]
 [ 5.55111512e-17  5.55111512e-17  5.61554755e-02]
 [ 1.11022302e-16 -1.11022302e-16  3.81208829e-02]]

Après itération 3:
Matrice Q mise à jou

### e. À l’aide de la matrice utilisée en $\mathbf{d}$, illustrez comment la multiplication successive des matrices $\mathbf{Q_i}$ triangularise progressivement la matrice $\mathbf{A}$. Dans l’élan, assurez-vous que les matrices $\mathbf{Q}$ et $\mathbf{R}$ obtenues sont bien orthogonale et triangulaire supérieure, respectivement.


# Question 2 : Mesures imprécises dans un jeu de bataille navale

### a. Modifiez votre code de décomposition QR pour qu’il retourne la décomposition QR réduite de la matrice d’entrée lorsque l’argument additionnel *reduite=True* lui est passé.


### b. Utilisez votre code pour résoudre approximativement l’équation suivante avec les données de bataille_navale_equipe015.csv.

$$\underbrace{\left[\begin{array}{ccc}
1 & x_1 & x_1^2 \\
1 & x_2 & x_2^2 \\
\vdots & \vdots & \vdots \\
1 & x_n & x_n^2
\end{array}\right]}_{\mathbf{X}}\left[\begin{array}{l}
\alpha_0 \\
\alpha_1 \\
\alpha_2
\end{array}\right]=\underbrace{\left[\begin{array}{c}
y_1 \\
y_2 \\
\vdots \\
y_n
\end{array}\right]}_{\mathbf{Y}}$$

### c. Tracez les données (cercles noirs) et la solution estimée de la trajectoire(ligne pleine de la couleur de votre choix) donnée par l’équation suivante:

$$y(x) = \alpha_0 + \alpha_1 x + \alpha_2 x^2$$

### d. Obtenez la position d’impact du projectile (à y = 0) en résolvant l’équation quadratique $y(x) = \alpha_0 + \alpha_1 x + \alpha_2 x^2$ pour x à l’aide d’une implémentation personnelle de la méthode de la bissection. Comparez votre solution avec celle obtenue en résolvant cette même équation analytiquement. Considérant que votre embarcation se situe à la position (x, y) = (0, 0), quelle est la distance horizontale vous séparant du point d’impact ?

# Question 3: Modèle épidemiologique SIR sur réseau

### a) Trouvez analytiquement toutes les solutions de l’équation cubique $$u = \frac{1}{[1+T(\kappa-1)(1-u)]^2} \equiv f(u)$$

On commence par modifier l'équation en une équation polynomiale de 3e degré.
En multipliant $u$ par le dénominateur, on obtient:
$$u[1+T(\kappa-1)(1-u)]^2=1$$
On remplace $A=T(\kappa-1)$ pour simplifier les calculs.
On développe le terme au carré et on redéveloppe l'équation en mettant tous les termes du même côté:
$$u[(1+a)^2-2A(1+A)u+A^2u^2]=1$$
$$A^2u^3-2A(1+A)u^2+(1+A)^2u-1=0$$
On souhaite ainsi résoudre l'équation cubique.
On remarque rapidement qu'on peut factoriser $(u-1)$, ce qui revient à dire que $u_1=1$ est solution. Effectivement:
$$A^2(1)^3-2A(1+A)(1)^2+(1+A)^2(1)-1=A^2-2A-2A^2+q+2A+A^2-1=0$$
L'équation devient alors:
$$(u-1)(A^2u^2-A^2u+1)$$
On résoud ainsi la deuxième partie de l'équation, soit l'équation quadratique. On obtient:
$$u_{2,3}=\frac{A^2\pm\sqrt{A^4-4A^2}}{2A^2}=\frac{1\pm\sqrt{1-4/A^2}}{2}$$
Ainsi, les solutions analytiques sont, avec $A=T(\kappa-1)$:
$$u_1 = 1$$
$$u_2=\frac{1\pm\sqrt{1-4/A^2}}{2} = \frac{1\pm\sqrt{1-4/(T(\kappa-1))^2}}{2}$$
$$u_3 =\frac{1\pm\sqrt{1-4/A^2}}{2} = \frac{1\pm\sqrt{1-4/(T(\kappa-1))^2}}{2}$$


### b. Démontrez laquelle des solutions obtenues précédemment (ou une combinaison de celles-ci) correspond à u, soit la solution recherchée de l’équation

### c. Tracez $R_{\infty}$ en fonction de T et identifiez tout changement qualitatif de $R_{\infty}$. Comment interprétez-vous ce changement (ou cette absence de changement) ?

### d. Résolvez numériquement l’équation à l’aide d’implémentations personnelles de la méthode par relaxation et de la méthode de Newton-Raphson pour 20 valeurs de T uniformément distribuées dans l’intervalle [0, 1].